# Site settings
title: Irreverent and Inappropriate
subtitle: The record of one mans descent in to madness...
email: blog@nubenu.net
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nubenu.net" # the base hostname & protocol for your site
twitter_username: neilcford
github_username:  neilcford

# Build settings
markdown: kramdown
